guide/Channel/closeTicket.md
guide/Channel/newTicket.md
guide/Channel/useChannel.md
guide/Message/interactionDelete.md
guide/Message/interactionEdit.md
guide/Message/interactionId.md
guide/Message/interactionReply.md
guide/Message/newTicket.md
guide/Message/newTicket.md.bak
guide/Message/sendWebhook.md
guide/Useful/spread.md
guide/regexMatch.md

$spread
$regexmatch
$interactionreply/delete/edit/id
$new/closeTicket
$sendWebhook
$usechannel

Added 10 new functions

---

guide/Text/Array/advancedTextSplit.md
guide/Text/Array/arrayFilter.md
guide/Text/Array/arrayGet.md
guide/Text/Array/arrayInclude.md
guide/Text/Array/arrayJoin.md
guide/Text/Array/arrayLength.md
guide/Text/Array/arrayMap.md
guide/Text/Array/arrayPush.md
guide/Text/Array/arrayRemove.md
guide/Text/Array/arraySearch.md
guide/Text/Array/arraySet.md
guide/Text/Array/arrayShift.md
guide/Text/Array/arrayShuffle.md
guide/Text/Array/arraySlice.md
guide/Text/Array/arraySort.md
guide/Text/Array/arrayUnshift.md
guide/Text/Array/concatTextSplit.md
guide/Text/Array/editTextSplitElement.md
guide/Text/Array/findTextSplitIndex.md
guide/Text/Array/removeTextSplitElement.md
guide/Text/Array/spliceTextJoin.md

$splicetextjoin
$findTextSplitIndex
$arrayShuffle
$arraySort
$editTextSplitElement
$arrayUnshift
$arraySlice
$arrayShift
$arraySet
$arrayPush
$arrayPop
$arrayMap
$arrayLength
$arrayJoin
$arrayGet
$arrayFilter
$arraySearch
$arrayRemove
$arrayInclude
$advancedTextSplit
$removeTextSplitElement
$removeSplitTextElement
$concatTextSplit

Added all 21 missing array/textsplit funcions

---

guide/Text/Components/addButton.md
guide/Text/Components/awaitButton.md
guide/Text/Components/disableButton.md
guide/Text/Components/editButton.md
guide/Text/Components/removeButton.md
guide/Text/Components/removeButtons.md
guide/Text/ObjectCreate.md
guide/Text/ObjectGet.md
guide/Text/ObjectKeys.md
guide/Text/ObjectSet.md
guide/Text/ObjectValues.md
guide/Text/createObject.md
guide/Text/getObject.md
guide/Text/getObjectKeys.md
guide/Text/getObjectProperty.md

$removeButton
$editButton
$addButton
$awaitButton
$disableButton
$removeButtons
$getObject
$createObject
$ObjectGet
$ObjectSet
$ObjectCreate
$ObjectValues
$ObjectKeys
$getObjectProperty
$getObjectKeys
$addObjectProperty

Added 15 new functions

---

guide/Text/Array/arrayGet.md
guide/Text/Components/awaitButton.md
guide/Text/Math/sub.md
guide/Text/Object/ObjectGet.md

in Sub, awaitbutton, objectget, and arrayget

fixed some visual bugs

---

guide/Variables/let.md

I corrected the spelling error of "retrive" to "retrieve"

Spelling Error Correction

---

guide/Bot/botCount.md
guide/Bot/clientID.md
guide/Bot/ping.md
guide/Bot/ram.md
guide/Bot/serverCount.md
guide/Bot/uptime.md
guide/Channel/channel.md
guide/Channel/channelCategoryID.md
guide/Channel/channelCount.md
guide/Channel/channelExists.md
guide/Channel/channelID.md
guide/Channel/channelName.md
guide/Channel/channelType.md
guide/Channel/channelUsed.md
guide/Channel/clear.md
guide/Channel/closeTicket.md
guide/Channel/createChannel.md
guide/Channel/deleteChannels.md
guide/Channel/editChannel.md
guide/Channel/eventChannelID.md
guide/Channel/findChannel.md
guide/Channel/modifyChannelPerms.md
guide/Channel/newTicket.md
guide/Channel/useChannel.md
guide/Channel/voiceChannelID.md
guide/CodeReferences/ref.channel_types.md
guide/README.md

This is my first pull request, if there is anything you need, let me know!

Documentation Optimisation 

---

guide/Message/createWebhook.md

Header fix

---

guide/Channel/serverChannels.md

Added lists of parameters for "info" and "type".
Added $categoryChannels as related function

Parameter choices for $serverChannel

---

guide/Unclassified/onlyIfMessageContains.md

Example + description rephrase

Onlyifmessagecontains

---

guide/CodeReferences/ref.message_curl_format.md

New line argument accepts only (yes/no)
Added disabled(yes/no)

Fixed {button}

---

guide/Date/timezone.md

The first word in timezone is Region

---

guide/Channel/modifyChannelPerms.md

After running into an issue with the bot asked to set a permission it didn't had, I'd like to read this on the Docs since I didn't know too

Added an info about bot permissions

---

guide/Useful/suppressErrors.md

As of Mido wrote in the support channel
"suppressErrors must be before the error so better put it on top"

Fixed wrong position of suppressErrors

---

guide/Text/Embed/example.md

Finished example.md for the documentation

example.md Finished

---

guide/Useful/forEach.md

the default is actually ;
not space

typo fix + false information

---

guide/Guide/1.create.md
guide/Other/ratelimits.md

Text style changes in guide/Guide/1.create.md and guide/Other/ratelimits.md
Makes explanations of rate limits more explicit.
Add explanation of function cooldown actions on reaching: 
1. function cooldown
2. function limit

Update create.md and ratelimits.md

---

guide/Text/findChars.md

fix example of findChars

---

guide/Member/authorAvatar.md
guide/Member/authorID.md
guide/Member/mention.md

1. Clarify the wording of functions descriptions to unify the style
1. Add more examples for `$authorAvatar` to show in details use of the function
2. Make examples more interactive using discord components instead of screenshots

Bring up to the same style $authorID related functions

---

guide/Trigger/button.md
guide/Trigger/roleaddremove.md
guide/Trigger/word.md
guide/Tutorials/3.report.md

Edited the following docs:
+ Word (rewrite)
> Moved and edited on examples to Tutorials and Examples
+ Button (rewrite)
+ Role (added summary)

Triggers improvement

---

guide/Guide/4.template.md

Added a video previews, and a section about submitting own templates

templates improvement

---

guide/Guide/5.comment.md

Used discord-messages instead of pictures and added a note about the ctrl+/ keystroke

small changes to 5.comment.md

---

guide/.vuepress/config.js

Urgent invite update

---

guide/Trigger/library.md

This PR:
- Rewrites the explanations to make them a bit clearer (hopefully)
- Fixes punctuation
- Fixes the link to the **$includeLibrary** function at the bottom of the **Triggers/library** page.
I'm new to contributing via PRs, so please bear with me ^^°

Rewrite Library Trigger
